export type GarmentCategory = "top" | "outerwear" | "dress" | "bottom";

/**
 * What a garment image actually is.
 *
 * Hosted try-on models are trained on **photographs of real garments laid
 * flat**. Feeding one vector artwork does not fail — it returns a confident,
 * useless render, having charged for it. So the kind is recorded rather than
 * assumed, and providers that need photography check it.
 */
export type GarmentImageKind = "photograph" | "illustration";

/**
 * A real image of the garment, as distinct from the `art` used for the picker
 * thumbnail and the offline mock.
 */
export interface GarmentImage {
  /** Absolute URL, or a site-relative path served from `public/`. */
  url: string;
  kind: GarmentImageKind;
  /**
   * Provenance and licence. Required, and it mirrors `SizeChart.verified`: the
   * point is that nothing whose rights are unclear can ship without someone
   * having written down what they are. Retailer product photography is
   * copyrighted — scraping it is not a shortcut available here.
   */
  licence: string;
}

/**
 * A garment in the catalog.
 *
 * `art` is inline SVG markup drawn in a 0 0 100 140 coordinate space. It is the
 * single source of truth for the garment's appearance: the picker renders it as
 * a thumbnail, and the mock try-on provider composites the same markup over the
 * person photo. Keeping one copy avoids the thumbnail and the result drifting.
 */
export interface Garment {
  id: string;
  name: string;
  category: GarmentCategory;
  /** Swatch shown in the picker chrome. Any CSS color. */
  accent: string;
  art: string;
  /**
   * Where the art sits on the person photo, as fractions (0-1) of the photo's
   * width and height. Origin is the top-left of the photo.
   */
  fit: { x: number; y: number; width: number; height: number };
  /**
   * The real garment image every hosted try-on model needs. Absent today for
   * every garment in the catalogue — see gate G16. `art` cannot substitute:
   * it is vector artwork authored for compositing, not a photograph.
   */
  image?: GarmentImage;
}

export interface TryOnRequest {
  /** The person photo, as a `data:image/...` URL. */
  personImage: string;
  /** Natural pixel dimensions of `personImage`, measured by the client. */
  personWidth: number;
  personHeight: number;
  garmentId: string;
}

export interface TryOnResult {
  /** The rendered try-on image, as a data URL. */
  image: string;
  garmentId: string;
  /** Which provider produced this, e.g. "mock" or "replicate". */
  provider: string;
  /** Wall-clock time the provider took, in milliseconds. */
  elapsedMs: number;
  /**
   * Set by providers that do not perform real garment fitting, so the UI can
   * say so rather than passing a placeholder off as inference.
   */
  simulated?: boolean;
  /**
   * Whether the image was generated by a model. Drives the visible
   * "AI-generated" label required by `docs/03-compliance-uk.md` §4 — provenance
   * metadata such as C2PA is not disclosure to a human.
   *
   * Distinct from `simulated`: the mock composites fixed artwork, so it is
   * neither a real fit nor AI-generated, and labelling it as generated would be
   * its own false claim.
   */
  aiGenerated?: boolean;
}
